language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: wtO/vNjs+yekLK3Bk8cWO1yt32aZF1nTthKoLIdfHHBOCawE9zrccGHVz4EabvI3Q6n8JipDbrwa2aEqc+p2JlPlzO2cmoLzr6rIcPu46SMMG8tt8Api3v31JLUwGiy5llhwHU84FeNx4XW1IvOevQClA9uXbFH2ldWyEj6rn+MHj1Ve8JRuwB0JkxytyFPCGEdx904D9dP2IsoG0qtsjmlLUDFOZzYrrUDdCICAMa99TPoo7/lQI9IwuH8EYSslG5YK7Uwsx6v0a9tdUJKkjGrATctytq7+pYPeaiGv7fMVKw8qxmLaf+MadDf+ihuGdE5sUT0yNu9mZkIz2TYbsI72NIBjHjlNU0g65Ili/6xT9YSVAt/Be3jaiS6F5KqxwdB/fZ45koNk6v7W2/JS8o7E6po+iWmcxOacJH2ZB5VVpTOelX98c6mF9223OdqvJqQBYbaeyxD/p6eHDuyRrg9XaYxuwSSP7PScJBXVzLX8Z6zJYzS8WQ0wd1nIjdvemOpLFBI1/0fI+C2znR6P8BoYDCJAnDqM9Tns9XJuQ5zlVA4D7pEp2x5Z53Oblv97f9VKnW5N0omdFzcKDOHF2mdHXsnUfjQIONixff3yraDBaYiapjfn/FVmoTKuC8gE0o2vDOUYQRrW/etbTWrMWvwfWlVM1DIpfVypFJR8Ewk=
  app: polar-plains-35991
