language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: DV5NOSJhXdUMiXGV4+xTIgHz2IfwgJ3FQ5aW/U6u4ZJd5Ug80GrtYRzP3UI9DFhzedJTcLGsFP/Bex96nBH1fxX/peDyNv5cdfhJnoZ1GCNAoUtBLQMb5QwA44xh9M3KLL3yN11yubFeGS8rmqBiYF+628u3Q+VY/BsjdGTT66zqry2G+oEQhCnqhtq7KvmviEWhqcPpzpVh0pe8FwunsXCJPzemHLTlawddEULmoCcvUSbML7bab1rZvgzpmOJ+sO0eXeFPS4oVrvULwY691U8Uq9pnZis2Wo4d+x80b5LQIVwOSFVB8LlFNIu4L2VvZPgdGiaJ5aZo7XK7LcZw9WlegJt2nTM1SOdYXZ0fo5jde6bVdhzMIdwTo+JSXA9jRN6ihg6h+mPpwPKhhBdlFshjk2KUnskajDkud++YnU5fKSx9ASdt2GeL/v54SEcwYQn+tCCB1s8CjXrFKGIWqSivUPoRwK2bWV+htAciFy9ymP70LI9mzJwN2Xuth1d8+yspo/dxq+BI2pp/tu45cawoKUpQ9lNvgohq/nNOzIzKPrFC5YQMuHFmvrUyo1RgY5qdRUNof8ajiyXq0e39yNS/l9HNiyNjAPvAekSWjy74REPSmLwzq467MArXPS/Wr6uCvAeYve+Lfv242ZUN4r0lAJ/tUPCKK1xA940MUlg=
  app: polar-plains-35991
  on:
    repo: dixita0607/test-ci
